package prv.saevel.drools.playground.rules

import prv.saevel.drools.playground.services.model.User;
import prv.saevel.drools.playground.services.model.Account;
import prv.saevel.drools.playground.services.model.Account
import prv.saevel.drools.playground.persistence.model.AccountType;

global prv.saevel.drools.playground.services.AccountService accountService;

rule "DefaultAccount"
    when
        user : User(anyUsername : username, anyPassword : password)
    then
        Account defaultAccount = accountService.createDefaultAccount(user, AccountType.BASIC);
        insert(defaultAccount);
    end