package prv.saevel.drools.playground.rules

import prv.saevel.drools.playground.services.model.User;
import prv.saevel.drools.playground.persistence.model.AccountType;
import prv.saevel.drools.playground.services.model.Account;
import java.util.Collections
import java.util.Optional
import java.util.stream.Collectors;

global prv.saevel.drools.playground.services.AccountService accountService;
global prv.saevel.drools.playground.persistence.model.AccountType defaultAccountType;

rule "YouthAccountType"
    when
        user : User(anyUsername : username, anyPassword : password, age <= 26)
    then
        insert(AccountType.YOUTH);
    end

rule "DefaultAccountType"
    when
        user : User(anyUsername : username, anyPassword : password, age > 26)
    then
        insert(defaultAccountType);
    end

rule "DefaultAccount"
    when
        user : User(anyUsername : username, anyPassword : password, anyAge: age)
        accountType : AccountType()
    then
        Account defaultAccount = accountService.createDefaultAccount(user, accountType);
        Optional.ofNullable(defaultAccount).ifPresent(account -> user.addAccount(account));
    end